### ISSUE TITLE
Outputs aren't looking like original

### ISSUE THREAD

**Issue by crahal** [centre-for-care/nrobust#3]
replications on full samples, even for fullest part of the curves

**Comment by dhvalden** [comment]
fixed in commit: 1082387a2ac04bbe4d60d2c51652618d3fe5e2af

### Some issues fixed included: 
- Ambiguous returning in several functions.
- Constant added to the dataset in the `OLSRobust.fit()` function now removed as it was interfering with the estimation.
- Not an issue, but a mistake: `OLSRobust()' initialised with y, x variables in the wrong order in the examples script(). I recommend using named argument always.
